# Generated by Django 3.2.12 on 2024-06-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=25)),
                ('duration', models.DurationField(max_length=5)),
                ('description', models.TextField()),
                ('fee', models.PositiveSmallIntegerField()),
                ('code', models.PositiveSmallIntegerField()),
                ('instructor', models.CharField(max_length=20)),
                ('content', models.TextField()),
                ('department', models.CharField(max_length=25)),
                ('capacity', models.PositiveSmallIntegerField()),
            ],
        ),
    ]
