# Generated by Django 3.2.12 on 2024-06-17 18:32

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Class',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('class_name', models.CharField(max_length=20)),
                ('Instructor', models.CharField(max_length=50)),
                ('description', models.TextField()),
                ('class_duration', models.DurationField()),
                ('class_capacity', models.PositiveSmallIntegerField()),
                ('course', models.CharField(max_length=20)),
                ('course_code', models.PositiveIntegerField()),
            ],
        ),
    ]
